In [3]:
import os
import pandas as pd
import glob

In [1]:


def merge_csv_files(root_folder):
    # 모든 CSV 파일의 경로를 저장할 리스트
    all_csv_files = []
    
    # 주어진 폴더와 그 하위 폴더를 순회하며 CSV 파일 찾기
    for root, dirs, files in os.walk(root_folder):
        for file in files:
            if file.endswith('.csv'):
                all_csv_files.append(os.path.join(root, file))
    
    # 찾은 CSV 파일이 없으면 오류 메시지 출력
    if not all_csv_files:
        print("CSV 파일을 찾을 수 없습니다.")
        return None
    
    # 모든 CSV 파일을 데이터프레임으로 읽어 리스트에 저장
    df_list = [pd.read_csv(file) for file in all_csv_files]
    
    # 모든 데이터프레임을 하나로 합치기
    merged_df = pd.concat(df_list, ignore_index=True)
    
    return merged_df

# 사용 예시
root_folder = '생성형AI분야_로우데이터/제주_관광_데이터'  # 여기에 실제 폴더 경로를 입력하세요
result = merge_csv_files(root_folder)

if result is not None:
    print(f"병합된 데이터프레임의 shape: {result.shape}")
    # 결과를 새로운 CSV 파일로 저장
    result.to_csv('merged_output.csv', index=False)
    print("병합된 CSV 파일이 'merged_output.csv'로 저장되었습니다.")

병합된 데이터프레임의 shape: (946198, 42)
병합된 CSV 파일이 'merged_output.csv'로 저장되었습니다.

In [139]:
org = pd.read_csv('merged_output.csv')
orgad = org.drop_duplicates('ADDR')

C:\Users\yunji\AppData\Local\Temp\ipykernel_14444\2315147064.py:1: DtypeWarning: Columns (0,2,3,26,27,28,32,34,36,40) have mixed types. Specify dtype option on import or set low_memory=False.
  org = pd.read_csv('merged_output.csv')

In [7]:
orgad['ADDR'][253:303]

265            제주특별자치도 서귀포시 대정읍 마라로 153
266               제주특별자치도 제주시 516로 2480
267           제주특별자치도 서귀포시 안덕면 상천리 산 83
268            제주특별자치도 제주시 한경면 저지리 산 56
269        제주특별자치도 제주시 조천읍 선흘남4길 264-17
270            제주특별자치도 서귀포시 남원읍 남조로 973
271             제주특별자치도 서귀포시 막숙포로37번길 2
272          제주특별자치도 제주시 한림읍 갯거리오름길 114
273            제주특별자치도 제주시 구좌읍 만장굴길 182
274             제주특별자치도 서귀포시 토평로50번길 31
275       제주특별자치도 서귀포시 남원읍 하례망장포로 65-13
276            제주특별자치도 서귀포시 표선면 표선리 산 2
277             제주특별자치도 제주시 구좌읍 구좌로 142
278            제주특별자치도 서귀포시 남원읍 서성로 755
279                 제주특별자치도 제주시 월광로 147
280          제주특별자치도 제주시 애월읍 소길남길 244-5
281        제주특별자치도 제주시 구좌읍 비자림로 2134-47
282            제주특별자치도 제주시 한림읍 명월리 2236
283              제주특별자치도 제주시 한림읍 명월로 71
284           제주특별자치도 서귀포시 성산읍 서성일로 260
285             제주특별자치도 서귀포시 산록남로 (색달동)
286         제주특별자치도 서귀포시 대정읍 상모리 3540-2
287         제주특별자치도 서귀포시 대정읍 신영로36번길 48
288           제주특별자치도 서귀포시 표선면 성읍리 산 22
289              제주특별자치도 제주시 추자면 신양리 56
290        제주특별자치도 제주시 조천읍 선흘리 산26번지 일대
291           제주특별자치도 서귀포시 표선면 번영로 2454
292            제주특별자치도 제주시 구좌읍 김녕리 2723
293    제주특별자치도 서귀포시 안덕면 신화역사로586번길 21-7
294            제주특별자치도 서귀포시 대정읍 무릉리 산 1
295         제주특별자치도 서귀포시 대정읍 중산간서로 2868
297            제주특별자치도 서귀포시 안덕면 병악로 420
298              제주특별자치도 서귀포시 중문관광로 205
299                제주특별자치도 제주시 애월읍 무수천길
300                  제주특별자치도 제주시 추자면 묵리
301            제주특별자치도 제주시 추자면 묵리 229-1
302           제주특별자치도 제주시 추자면 추자로 376-6
303           제주특별자치도 제주시 추자면 추자로 365-1
304            제주특별자치도 제주시 한림읍 금악리 3444
305              제주특별자치도 제주시 애월읍 곽지7길 1
306                 제주특별자치도 제주시 구좌읍 송당리
307                   제주특별자치도 서귀포시 칠십리로
308                제주특별자치도 제주시 거로남6길 13
309                 제주특별자치도 서귀포시 중정로 76
310                  제주시 한경면 중산간서로 3675
311           제주특별자치도 제주시 애월읍 수산리 산 1-1
312              제주특별자치도 제주시 애월읍 예원로 51
313         제주특별자치도 서귀포시 남원읍 남조로 988-11
314                 제주특별자치도 제주시 조천읍 교래길
315           제주특별자치도 서귀포시 인정오름로 387-63
Name: ADDR, dtype: object

In [141]:
orgad['ADR'] = False

C:\Users\yunji\AppData\Local\Temp\ipykernel_14444\882417010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orgad['ADR'] = False

In [33]:
orgad.columns

Index(['CL_CD', 'CL_NM', 'AREA_NM', 'ADDR', 'BASE_YEAR', 'BASE_MT',
       'ALL_TOTAL_CO', 'MON_VIEWS_CO', 'TUES_VIEWS_CO', 'WED_VIEWS_CO',
       'THUR_VIEWS_CO', 'FRI_VIEWS_CO', 'SAT_VIEWS_CO', 'SUN_VIEWS_CO',
       'JAN_VIEWS_CO', 'FEB_VIEWS_CO', 'MAR_VIEWS_CO', 'APR_VIEWS_CO',
       'MAY_VIEWS_CO', 'JUN_VIEWS_CO', 'JULY_VIEWS_CO', 'AUG_VIEWS_CO',
       'SEP_VIEWS_CO', 'OCT_VIEWS_CO', 'NOV_VIEWS_CO', 'DEC_VIEWS_CO',
       'TRRSRT_NM', 'TRRSRT_ADDR', 'ORIGIN_CL_NM', 'ANALS_BEGIN_DE',
       'ANALS_END_DE', 'AVRG_SCORE_VALUE', 'CORE_KWRD_CN', 'CORE_KWRD_CO',
       'AFRM_KWRD_CN', 'AFRM_KWRD_CO', 'NEGA_KWRD_CN', 'NEGA_KWRD_CO',
       'BASE_YM', 'SCORE_VALUE', 'MOP_CN', 'REGIST_DE', 'ADR'],
      dtype='object')

In [19]:
orgad.iloc[2, 3], orgad.iloc[2, 3].replace('제주특별자치도 ', '')

('제주특별자치도 서귀포시 1100로 1555', '서귀포시 1100로 1555')

In [143]:
import pandas as pd
import re
import numpy as np

def preprocess_address(address):
    # NaN 값 체크
    if pd.isna(address):
        return ''
    
    # 문자열로 변환
    address = str(address)
    
    # '제주특별자치도' 제거
    address = address.replace('제주특별자치도 ', '')
    
    # 괄호와 그 안의 내용 제거
    address = re.sub(r'\([^)]*\)', '', address)
    
    # 맨 뒤의 숫자나 '층', 'F'와 그 앞의 내용 제거
    address = re.sub(r'\s+\[층F]?.*$', '', address)
    
    # 연속된 공백을 하나의 공백으로 대체
    address = re.sub(r'\s+', ' ', address).strip()
    
    return address

In [87]:
# 전처리 함수 적용
orgad['ADR'] = orgad['ADDR'].str.replace('제주특별자치도 ', '', regex=False)

C:\Users\yunji\AppData\Local\Temp\ipykernel_14444\2715883022.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orgad['ADR'] = orgad['ADDR'].str.replace('제주특별자치도 ', '', regex=False)

In [145]:
orgad['ADR'] = orgad['ADDR'].apply(preprocess_address)

C:\Users\yunji\AppData\Local\Temp\ipykernel_14444\1741962537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orgad['ADR'] = orgad['ADDR'].apply(preprocess_address)

In [147]:
orgad[['ADDR','ADR']][:-50]

,ADDR,ADR
0,제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트),서귀포시 대정읍 글로벌에듀로 234
1,제주특별자치도 제주시 애월읍 애월로1길 22,제주시 애월읍 애월로1길 22
2,제주특별자치도 서귀포시 1100로 1555,서귀포시 1100로 1555
3,제주특별자치도 서귀포시 색달동 산 1-2,서귀포시 색달동 산 1-2
4,제주특별자치도 제주시 명림로 584 (봉개동),제주시 명림로 584
...,...,...
34194,제주특별자치도 제주시 한라대학로 75,제주시 한라대학로 75
34259,제주특별자치도 제주시 애월읍 평화로 2715 행복기숙사 2호관 2층 1호,제주시 애월읍 평화로 2715 행복기숙사 2호관 2층 1호
34335,제주특별자치도 서귀포시 이어도로 297 (하원동) 1층,서귀포시 이어도로 297 1층
34487,제주특별자치도 서귀포시 남원읍 태신해안로 115,서귀포시 남원읍 태신해안로 115
34535,제주특별자치도 제주시 조천읍 번영로 1278-169 (대흘리),제주시 조천읍 번영로 1278-169

In [149]:
def preprocess_address(address):
    # NaN 값 체크
    if pd.isna(address):
        return ''
    
    # 문자열로 변환
    address = str(address)
    
    # '제주특별자치도' 제거
    address = address.replace('제주특별자치도 ', '')
    
    # # '제주' 제거 (일부 주소에서 '제주특별자치도' 대신 '제주'로 시작하는 경우)
    # address = address.replace('제주 ', '')
    
    # 괄호와 그 안의 내용 제거
    address = re.sub(r'\([^)]*\)', '', address)
    
    # 주소를 공백으로 분리
    parts = address.split()
    
    # 뒤에서부터 검사하여 조건에 맞는 마지막 단어 찾기
    for i in range(len(parts) - 1, -1, -1):
        if re.match(r'^\d{2,}$', parts[i]) or '-' in parts[i]:
            # 조건에 맞는 단어까지 슬라이스
            cleaned_address = ' '.join(parts[:i+1])
            break
    else:
        # 조건에 맞는 단어를 찾지 못한 경우, 원래 주소 사용
        cleaned_address = address
    
    # 연속된 공백을 하나의 공백으로 대체
    cleaned_address = re.sub(r'\s+', ' ', cleaned_address).strip()
    
    return cleaned_address

In [151]:
orgad['ADR'] = orgad['ADDR'].apply(preprocess_address)

C:\Users\yunji\AppData\Local\Temp\ipykernel_14444\1741962537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orgad['ADR'] = orgad['ADDR'].apply(preprocess_address)

In [153]:
orgad[['ADDR','ADR']][:50]

                                  ADDR                     ADR
0   제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트)     서귀포시 대정읍 글로벌에듀로 234
1             제주특별자치도 제주시 애월읍 애월로1길 22        제주시 애월읍 애월로1길 22
2              제주특별자치도 서귀포시 1100로 1555         서귀포시 1100로 1555
3               제주특별자치도 서귀포시 색달동 산 1-2          서귀포시 색달동 산 1-2
4            제주특별자치도 제주시 명림로 584 (봉개동)             제주시 명림로 584
5                   제주특별자치도 제주시 신산로 82              제주시 신산로 82
6           제주특별자치도 서귀포시 남원읍 신례리 산 2-1      서귀포시 남원읍 신례리 산 2-1
7           제주특별자치도 제주시 애월읍 천덕로 880-24      제주시 애월읍 천덕로 880-24
8           제주특별자치도 서귀포시 대정읍 일주서로 2497      서귀포시 대정읍 일주서로 2497
9                   제주특별자치도 제주시 서사로 28              제주시 서사로 28
10         제주특별자치도 서귀포시 대정읍 최남단해안로 128     서귀포시 대정읍 최남단해안로 128
11         제주특별자치도 제주시 애월읍 애월해안로 516-7     제주시 애월읍 애월해안로 516-7
12           제주특별자치도 서귀포시 1100로 453-95       서귀포시 1100로 453-95
14            제주특별자치도 제주시 한경면 청수서5길 63        제주시 한경면 청수서5길 63
16           제주특별자치도 제주시 애월읍 봉성리 산 125       제주시 애월읍 봉성리 산 125
17          제주특별자치도 서귀포시 남원읍 남위남성로 168      서귀포시 남원읍 남위남성로 168
18        제주특별자치도 서귀포시 표선면 남조로 1487-73    서귀포시 표선면 남조로 1487-73
19            제주특별자치도 서귀포시 표선면 녹산로 554        서귀포시 표선면 녹산로 554
20                제주특별자치도 서귀포시 대정읍 가파리            서귀포시 대정읍 가파리
21         제주특별자치도 서귀포시 대정읍 최남단해안로 120     서귀포시 대정읍 최남단해안로 120
22             제주특별자치도 서귀포시 대정읍 마라로 58         서귀포시 대정읍 마라로 58
23               제주특별자치도 서귀포시 호근동 2112           서귀포시 호근동 2112
24                 제주특별자치도 서귀포시 중정로 22             서귀포시 중정로 22
25              제주특별자치도 서귀포시 효돈순환로 441          서귀포시 효돈순환로 441
27           제주특별자치도 서귀포시 남원읍 하례중앙로 95       서귀포시 남원읍 하례중앙로 95
28             제주특별자치도 제주시 구좌읍 평대7길 34         제주시 구좌읍 평대7길 34
29           제주특별자치도 제주시 애월읍 금성1길 29-3       제주시 애월읍 금성1길 29-3
30            제주특별자치도 제주시 조천읍 남조로 1904        제주시 조천읍 남조로 1904
31         제주특별자치도 서귀포시 대정읍 상모대서로 43-3     서귀포시 대정읍 상모대서로 43-3
32                제주특별자치도 서귀포시 말질로 290            서귀포시 말질로 290
33            제주특별자치도 서귀포시 강정통물로 (강정동)              서귀포시 강정통물로
34                  제주특별자치도 제주시 구산로 26              제주시 구산로 26
35      제주특별자치도 서귀포시 표선면 성읍이리로57번길 162  서귀포시 표선면 성읍이리로57번길 162
36                     제주특별자치도 제주시 봉개동                 제주시 봉개동
37                제주특별자치도 제주시 매촌1길 3-1            제주시 매촌1길 3-1
38                 제주특별자치도 제주시 영평길 269             제주시 영평길 269
39           제주특별자치도 서귀포시 안덕면 동광리 산 94       서귀포시 안덕면 동광리 산 94
40          제주특별자치도 제주시 조천읍 선교로 569-36      제주시 조천읍 선교로 569-36
41                   제주특별자치도 서귀포시 516로               서귀포시 516로
42           제주특별자치도 제주시 구좌읍 송당리 산 145       제주시 구좌읍 송당리 산 145
43                  제주특별자치도 제주시 대원길 58              제주시 대원길 58
44           제주특별자치도 제주시 명림로 520 (봉개동)             제주시 명림로 520
45          제주특별자치도 서귀포시 안덕면 일주서로 1611      서귀포시 안덕면 일주서로 1611
46                  제주시 한경면 중산간서로 3169      제주시 한경면 중산간서로 3169
47              제주특별자치도 서귀포시 남성로 (서홍동)                서귀포시 남성로
48               제주특별자치도 서귀포시 서홍로 4-42           서귀포시 서홍로 4-42
49          제주특별자치도 서귀포시 남원읍 하례로 393-1      서귀포시 남원읍 하례로 393-1
50                     제주특별자치도 제주시 우도면                 제주시 우도면
51               제주특별자치도 제주시 우도면 우도해안길           제주시 우도면 우도해안길
52                    제주특별자치도 서귀포시 하효동                서귀포시 하효동

In [155]:
orgad = orgad.reset_index().drop('index',axis=1); orgad

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,BASE_MT,ALL_TOTAL_CO,MON_VIEWS_CO,TUES_VIEWS_CO,WED_VIEWS_CO,...,CORE_KWRD_CO,AFRM_KWRD_CN,AFRM_KWRD_CO,NEGA_KWRD_CN,NEGA_KWRD_CO,BASE_YM,SCORE_VALUE,MOP_CN,REGIST_DE,ADR
0,c1,관광지,브랭섬홀아시아 아이스링크,제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트),2023.0,1.0,110.0,15.0,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서귀포시 대정읍 글로벌에듀로 234
1,c1,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2023.0,1.0,68.0,11.0,14.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,제주시 애월읍 애월로1길 22
2,c1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2023.0,1.0,1587.0,313.0,283.0,222.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서귀포시 1100로 1555
3,c1,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2023.0,1.0,4075.0,662.0,643.0,599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서귀포시 색달동 산 1-2
4,c1,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2023.0,1.0,79.0,17.0,6.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,제주시 명림로 584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4552,c4,음식점,조천수산,제주특별자치도 제주시 조천읍 조천북1길 35-8,2023.0,12.0,3.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,제주시 조천읍 조천북1길 35-8
4553,c4,음식점,하양한,제주 제주시 조천읍 신북로 494-2 하양한,2023.0,12.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,제주 제주시 조천읍 신북로 494-2
4554,c4,음식점,행운문,제주특별자치도 제주시 애월읍 봉성로2길 34-3,2023.0,12.0,6.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,제주시 애월읍 봉성로2길 34-3
4555,c4,음식점,혼저,"제주특별자치도 제주시 한림읍 한림로 158 (금능리, 금능리 재즈클럽) 1F 혼저 ...",2023.0,12.0,89.0,16.0,12.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,제주시 한림읍 한림로 158
4556,NaN,공연전시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,친절,1.0,NaN,0.0,NaN,NaN,NaN,NaN,

In [157]:
# 라이브러리 설치
# !pip install googlemaps

# import 라이브러리
import googlemaps
import pandas as pd
from tqdm import tqdm

#예제 데이터 : df_shake
#컬럼 정보 : name, branch, addr

# API키 입력
mykey = "AIzaSyABLCKG6ZQk9cHsynEF6ufOjQ8WLq4kaiY"
maps = googlemaps.Client(key=mykey)  # my key값 입력

# 위도,경도 변환하는 함수 생성
def trans_geo(addr):
    try:
        geo_location = maps.geocode(addr)[0].get('geometry')
        lat = geo_location['location']['lat']
        lng =  geo_location['location']['lng']
        return [lat,lng]
    except:
        return [0,0]

# 실행
for idx, addr in enumerate(tqdm(orgad.loc[:,'ADR'])):
    orgad.loc[idx,'위도'] = trans_geo(addr)[0]
    orgad.loc[idx,'경도'] = trans_geo(addr)[1]

100%|██████████████████████████████████████████████████████████████████████████████| 4557/4557 [16:07<00:00,  4.71it/s]

In [173]:
orgad.query('위도 == 0')

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,BASE_MT,ALL_TOTAL_CO,MON_VIEWS_CO,TUES_VIEWS_CO,WED_VIEWS_CO,...,AFRM_KWRD_CO,NEGA_KWRD_CN,NEGA_KWRD_CO,BASE_YM,SCORE_VALUE,MOP_CN,REGIST_DE,ADR,위도,경도
2522,c4,음식점,망고봉봉,m.blog.naver.com/lidia3825,2023.0,1.0,36.0,2.0,10.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,m.blog.naver.com/lidia3825,0.0,0.0
4556,NaN,공연전시,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,0.0,NaN,NaN,NaN,NaN,,0.0,0.0

In [163]:
orgad.to_csv('관광_위도경도.csv', index=False)

In [165]:
sumdf = pd.merge(org, orgad[['ADDR', '위도', '경도']], on='ADDR', how='left');sumdf

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,BASE_MT,ALL_TOTAL_CO,MON_VIEWS_CO,TUES_VIEWS_CO,WED_VIEWS_CO,...,AFRM_KWRD_CN,AFRM_KWRD_CO,NEGA_KWRD_CN,NEGA_KWRD_CO,BASE_YM,SCORE_VALUE,MOP_CN,REGIST_DE,위도,경도
0,c1,관광지,브랭섬홀아시아 아이스링크,제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트),2023.0,1.0,110.0,15.0,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.290549,126.287508
1,c1,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2023.0,1.0,68.0,11.0,14.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.462334,126.310475
2,c1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2023.0,1.0,1587.0,313.0,283.0,222.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.345690,126.442659
3,c1,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2023.0,1.0,4075.0,662.0,643.0,599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.357524,126.462897
4,c1,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2023.0,1.0,79.0,17.0,6.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.430235,126.622796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946193,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,7.5,"수영장,여행,가격,도면",20231227.0,0.000000,0.000000
946194,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,10.0,새싹,20231228.0,0.000000,0.000000
946195,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,5.8,"금고,수영장,직원,깔끔,소음",20231229.0,0.000000,0.000000
946196,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,10.0,"수영장,청결,저렴,가격,편의점",20231230.0,0.000000,0.000000
946197,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,8.4,"가격,위생,화장실,머리카락,조명",20231231.0,0.000000,0.000000

In [175]:
sumdf[['ADDR', '위도', '경도']][:50]

                                  ADDR         위도          경도
0   제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트)  33.290549  126.287508
1             제주특별자치도 제주시 애월읍 애월로1길 22  33.462334  126.310475
2              제주특별자치도 서귀포시 1100로 1555  33.345690  126.442659
3               제주특별자치도 서귀포시 색달동 산 1-2  33.357524  126.462897
4            제주특별자치도 제주시 명림로 584 (봉개동)  33.430235  126.622796
5                   제주특별자치도 제주시 신산로 82  33.506398  126.533912
6           제주특별자치도 서귀포시 남원읍 신례리 산 2-1  33.333034  126.618066
7           제주특별자치도 제주시 애월읍 천덕로 880-24  33.418059  126.342056
8           제주특별자치도 서귀포시 대정읍 일주서로 2497  33.229146  126.262706
9                   제주특별자치도 제주시 서사로 28  33.509876  126.519536
10         제주특별자치도 서귀포시 대정읍 최남단해안로 128  33.210545  126.257605
11         제주특별자치도 제주시 애월읍 애월해안로 516-7  33.477420  126.359964
12           제주특별자치도 서귀포시 1100로 453-95  33.286149  126.444455
13           제주특별자치도 서귀포시 1100로 453-95  33.286149  126.444455
14            제주특별자치도 제주시 한경면 청수서5길 63  33.305488  126.249350
15            제주특별자치도 제주시 한경면 청수서5길 63  33.305488  126.249350
16           제주특별자치도 제주시 애월읍 봉성리 산 125  33.364338  126.355203
17          제주특별자치도 서귀포시 남원읍 남위남성로 168  33.290130  126.693124
18        제주특별자치도 서귀포시 표선면 남조로 1487-73  33.395663  126.670985
19            제주특별자치도 서귀포시 표선면 녹산로 554  33.393916  126.722409
20                제주특별자치도 서귀포시 대정읍 가파리  33.169734  126.271453
21         제주특별자치도 서귀포시 대정읍 최남단해안로 120  33.210545  126.257605
22             제주특별자치도 서귀포시 대정읍 마라로 58  33.119033  126.266657
23               제주특별자치도 서귀포시 호근동 2112  33.276757  126.526959
24                 제주특별자치도 서귀포시 중정로 22  33.247413  126.558709
25              제주특별자치도 서귀포시 효돈순환로 441  33.271280  126.607675
26              제주특별자치도 서귀포시 효돈순환로 441  33.271280  126.607675
27           제주특별자치도 서귀포시 남원읍 하례중앙로 95  33.269243  126.625429
28             제주특별자치도 제주시 구좌읍 평대7길 34  33.531003  126.843266
29           제주특별자치도 제주시 애월읍 금성1길 29-3  33.446855  126.299510
30            제주특별자치도 제주시 조천읍 남조로 1904  33.437190  126.670615
31         제주특별자치도 서귀포시 대정읍 상모대서로 43-3  33.226589  126.257380
32                제주특별자치도 서귀포시 말질로 290  33.227574  126.474739
33            제주특별자치도 서귀포시 강정통물로 (강정동)  33.235615  126.476943
34                  제주특별자치도 제주시 구산로 26  33.483031  126.537988
35      제주특별자치도 서귀포시 표선면 성읍이리로57번길 162  33.423227  126.771751
36                     제주특별자치도 제주시 봉개동  33.457132  126.613053
37                제주특별자치도 제주시 매촌1길 3-1  33.515904  126.589044
38                 제주특별자치도 제주시 영평길 269  33.478057  126.570011
39           제주특별자치도 서귀포시 안덕면 동광리 산 94  33.302672  126.332024
40          제주특별자치도 제주시 조천읍 선교로 569-36  33.456996  126.714306
41                   제주특별자치도 서귀포시 516로  33.351077  126.620716
42           제주특별자치도 제주시 구좌읍 송당리 산 145  33.450545  126.759568
43                  제주특별자치도 제주시 대원길 58  33.471792  126.535339
44           제주특별자치도 제주시 명림로 520 (봉개동)  33.444895  126.625681
45          제주특별자치도 서귀포시 안덕면 일주서로 1611  33.254725  126.345565
46                  제주시 한경면 중산간서로 3169  33.294111  126.232929
47              제주특별자치도 서귀포시 남성로 (서홍동)  33.242712  126.548847
48               제주특별자치도 서귀포시 서홍로 4-42  33.249797  126.554865
49          제주특별자치도 서귀포시 남원읍 하례로 393-1  33.282778  126.620079

In [169]:
sumdf.to_csv('관광_위도경도SUM.csv', index=False)

In [1]:
import pandas as pd

org = pd.read_csv('관광_위도경도SUM.csv'); org

C:\Users\yunji\AppData\Local\Temp\ipykernel_22416\3838302889.py:3: DtypeWarning: Columns (0,2,3,26,27,28,32,34,36,40) have mixed types. Specify dtype option on import or set low_memory=False.
  org = pd.read_csv('관광_위도경도SUM.csv'); org

,CL_CD,CL_NM,AREA_NM,ADDR,BASE_YEAR,BASE_MT,ALL_TOTAL_CO,MON_VIEWS_CO,TUES_VIEWS_CO,WED_VIEWS_CO,...,AFRM_KWRD_CN,AFRM_KWRD_CO,NEGA_KWRD_CN,NEGA_KWRD_CO,BASE_YM,SCORE_VALUE,MOP_CN,REGIST_DE,위도,경도
0,c1,관광지,브랭섬홀아시아 아이스링크,제주특별자치도 서귀포시 대정읍 글로벌에듀로 234(3번게이트),2023.0,1.0,110.0,15.0,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.290549,126.287508
1,c1,관광지,(주)제주해양레저 투명카약,제주특별자치도 제주시 애월읍 애월로1길 22,2023.0,1.0,68.0,11.0,14.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.462334,126.310475
2,c1,관광지,1100고지(휴게소),제주특별자치도 서귀포시 1100로 1555,2023.0,1.0,1587.0,313.0,283.0,222.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.345690,126.442659
3,c1,관광지,1100고지습지,제주특별자치도 서귀포시 색달동 산 1-2,2023.0,1.0,4075.0,662.0,643.0,599.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.357524,126.462897
4,c1,관광지,1112도로,제주특별자치도 제주시 명림로 584 (봉개동),2023.0,1.0,79.0,17.0,6.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.430235,126.622796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946193,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,7.5,"수영장,여행,가격,도면",20231227.0,0.000000,0.000000
946194,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,10.0,새싹,20231228.0,0.000000,0.000000
946195,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,5.8,"금고,수영장,직원,깔끔,소음",20231229.0,0.000000,0.000000
946196,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,10.0,"수영장,청결,저렴,가격,편의점",20231230.0,0.000000,0.000000
946197,NaN,관광호텔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,202312.0,8.4,"가격,위생,화장실,머리카락,조명",20231231.0,0.000000,0.000000

In [5]:
org.query('위도!=0').to_csv('관광지_위도경도SUM.csv', index=False)